### ISSUE TITLE
Codepush and Jitsi not compatible in release mode.

### ISSUE THREAD

**Issue by jerinjohnk** [skrafft/react-native-jitsi-meet#94]
## Description
In release version of android app crashes with error as soon as its opened
```
null is not an object (evaluating 'n.IsAndroid')

Module AppRegistry is not a registered callable module (calling runApplication)

null is not an object (evaluating 't.NativeModules.LocaleDetector.locale')
```

## Current behavior
Currently in app Codepush is added `android/app/src/main/java/com/docprime/MainApplication.java`
```
 @Override
        protected String getJSBundleFile() {
        return CodePush.getJSBundleFile();
        }
```

## Possible Solution
Commenting above snippet in android successfully builds android release

## Steps to reproduce
Add  `react-native-code-push`, complete its android installation and create a build.

# Environment details
 "react-native-code-push": "^5.5.1",
"react": "16.6.1",
"react-native": "^0.59.5",
"react-native-jitsi-meet": "^1.2.0",

Referencing similar error log issue https://github.com/microsoft/react-native-code-push/issues/1748

**Comment by skrafft** [comment]
Hi @jerinjohnk ,

You need to use the following code in  ``android/app/src/main/java/com/docprime/MainApplication.java``
```    
   @Override
    protected String getJSBundleFile() {
        return CodePush.getJSBundleFile("app.bundle");
    }
```

If you followed this plugin install doc, it should work (we're using both plugins in production)

**Comment by SeveHo** [comment]
Hi @skrafft, I have get exactly the same error for release builds but my app is not using codepush and I'm using version 2.1.1. Do you have an idea what else could cause this?

**Comment by skrafft** [comment]
@SeveHo 

Make sure you have followed all the steps in this section: https://github.com/skrafft/react-native-jitsi-meet#android-manual-install

**Comment by SeveHo** [comment]
Wow, I always thought that the steps of the manual install are only required when not using RN >= 60 auto linking feature.

It now works after applying step 2) of the manual install. The changes from the others steps where already automatically added after the package installation.

Maybe a hint could be useful that all changes described in [Android Manuall Install](https://github.com/skrafft/react-native-jitsi-meet#android-manual-install) need to be included even though automatic linking already does most if it.

Thanks a lot @skrafft !

**Comment by filipef101** [comment]
There should be a FAQ/compatibility list.
This is all because the the sdk is also made in react-native (react-native-ception ahah)
Where it points that if you use codepush you must use 
```
@Override
    protected String getJSBundleFile() {
        return CodePush.getJSBundleFile("app.bundle");
    }
```

And the "manual install" section should be "install on android" because it is needed, not optional...

Either way, thanks, and nice work <3

**Comment by tmjordan** [comment]
Hi @skrafft, thanks for this awesome library. I applied the fix for codepush, and my app is running well now. But it looks like codepush is not working anymore. My app does not receive codepush updates anymore. Can you help me please
```
@Override
    protected String getJSBundleFile() {
        return CodePush.getJSBundleFile("app.bundle");
    }
```

**Comment by mamoru0217** [comment]
@tmjordan 
Hi, I got a same problem but fixed it.
Please check the bundle file name emitted by codepush.
In my case, the file name was `index.android.bundle`, so I edit my app's code as following.

```diff
// app/build.gradle

project.ext.react = [
    entryFile: "index.js",
-    bundleAssetName: "app.bundle"
+    bundleAssetName: "index.android.bundle"
]
```

```diff
// app/src/main/java/com/cinemally/MainApplication.java

...

@Override
protected @Nullable String getBundleAssetName() {
-  return "app.bundle";
+  return "index.android.bundle";
}

@Override
protected String getJSBundleFile() {
-  return CodePush.getJSBundleFile("app.bundle");
+ return CodePush.getJSBundleFile("index.android.bundle");
}

...
```

I hope this fix your problem also.

**Comment by tmjordan** [comment]
Hi @mamoru0217 , thank you very much. Your solution is working.
You saved me :D

**Comment by davenlin19** [comment]
Thank you @skrafft You saved my life!

**Comment by davenlin19** [comment]
> Hi @jerinjohnk ,
> 
> You need to use the following code in `android/app/src/main/java/com/docprime/MainApplication.java`
> 
> ```
>    @Override
>     protected String getJSBundleFile() {
>         return CodePush.getJSBundleFile("app.bundle");
>     }
> ```
> 
> If you followed this plugin install doc, it should work (we're using both plugins in production)

@skrafft Do we need to do anything like that for IOS? My app can detect that there is a new version but not be able to use the new version. Thank you!

**Comment by skrafft** [comment]
Nope, normally, following Code Push doc and Jitsi meet doc work on iOS. Code Push does not work with debug mode though.

**Comment by dgreasi** [comment]
Hi guys. @skrafft Thanks for the good work on this project.

I was trying to use both react-native-code-push and react-native-jitsi-meet but with no success.

The library versions i use are the following:

```
"react-native": "0.63.3",
"react-native-code-push": "^7.0.1",
"react-native-jitsi-meet": (custom fork of 2.1.2), // simple changes on the waiting dialog, nothing major
``` 

At first i tried the approach that @skrafft recommended [here](https://github.com/skrafft/react-native-jitsi-meet/issues/94#issuecomment-572567766), but it seems that my code-push version uses a different file name as indicated by @mamoru0217. 

Thus, in that case tha app crashes immediately as the react-native-code-push searches for a different bundle name.

After that i tested the [approach](https://github.com/skrafft/react-native-jitsi-meet/issues/94#issuecomment-653860514) of @mamoru0217.

The result was a successful startup of the application as the code-push library found the bundle file, but when using the Jitsi meet library to join a videocall the app crashes, probably for the same reason, it searches for "app.bundle" instead of the "index.android.bundle" that we use.

I have been investigating for a couple of days now but with no result. Any thoughts?

**Comment by dgreasi** [comment]
The problem is at the command:
```
appcenter codepush release-react
```

Which will always run a "react-native bundle" and name the bundle as "index.android.bundle"

Thus, if i use [this](https://github.com/skrafft/react-native-jitsi-meet/issues/94#issuecomment-572567766) codepush will download the updated bundle but will fail to update due to different bundle names ("index.android.bundle" !== "app.bundle")

If i use [this](https://github.com/skrafft/react-native-jitsi-meet/issues/94#issuecomment-653860514) the jitsi-meet is crashing.

The solution was to keep [that](https://github.com/skrafft/react-native-jitsi-meet/issues/94#issuecomment-572567766) approach on the native android code and use the following commands for the codepush:

```
react-native bundle --platform android --entry-file index.js --bundle-output ./bundles/app.bundle --assets-dest ./bundles/ --dev false
appcenter codepush release -a APP_NAME -c ./bundles/ -t APP_VERSION -d Development
```

I tried to change the default bundle name of the "codepush release-react" command with no luck.

**Comment by hanifmhd** [comment]
> Hi guys. @skrafft Thanks for the good work on this project.
> 
> I was trying to use both react-native-code-push and react-native-jitsi-meet but with no success.
> 
> The library versions i use are the following:
> 
> ```
> "react-native": "0.63.3",
> "react-native-code-push": "^7.0.1",
> "react-native-jitsi-meet": (custom fork of 2.1.1), // simple changes to pass extra params, nothing major
> ```
> 
> At first i tried the approach that @skrafft recommended [here](https://github.com/skrafft/react-native-jitsi-meet/issues/94#issuecomment-572567766), but it seems that my code-push version uses a different file name as indicated by @mamoru0217.
> 
> Thus, in that case tha app crashes immediately as the react-native-code-push searches for a different bundle name.
> 
> After that i tested the [approach](https://github.com/skrafft/react-native-jitsi-meet/issues/94#issuecomment-653860514) of @mamoru0217.
> 
> The result was a successful startup of the application as the code-push library found the bundle file, but when using the Jitsi meet library to join a videocall the app crashes, probably for the same reason, it searches for "app.bundle" instead of the "index.android.bundle" that we use.
> 
> I have been investigating for a couple of days now but with no result. Any thoughts?

can you share your error log?
